name: Configurar agente de Azure en instancia EC2

on:
  workflow_dispatch:
    inputs:
      id-instance:
        description: "ID de la instancia EC2 a configurar"
        required: true
        default: ""
      docuement-name:
        description: "Nombre del documento SSM a utilizar"
        required: true
        default: ""
      region:
        description: "Región de AWS"
        required: true
        default: "us-east-1"
      

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Install AWS CLI
        run: pip install awscli

      - name: Config EC2 Instance
        run: |
          aws ssm send-command \
          --instance-ids "${{ github.event.inputs['stack-name']" \
          --document-name "${{ github.event.inputs['stack-name']" \
          --parameters '{
            "AzureOrgUrl": ["https://dev.azure.com/wilmersierralinux"],
            "AzurePAT": ["${{ secrets.AZURE_PAT }}"],
            "AgentPool": ["Pool-Agent-Aws"]
          }' \
          --cloud-watch-output-config '{
            "CloudWatchLogGroupName": "/aws/ssm/azure-agent-deployment",
            "CloudWatchOutputEnabled": true
          }'